### PR TITLE
MULTI

### PR DESCRIPTION
**Pull request by KuanHulio**
#### I have
* [x] made sure there are no pull requests that add this functionality.
* [x] read and followed the [contribution guidelines](https://github.com/LewisTehMinerz/PancakeDB/blob/master/CONTRIBUTING.md).
* [x] read and followed the [Code of Conduct](https://github.com/LewisTehMinerz/PancakeDB/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by KuanHulio** [comment]
@LewisTehMinerz can you check my logic in this?

What if, instead, we split ANDs and get the commands and run them through a forloop?

**Comment by LewisTehMinerz** [comment]
it could work...

**Comment by KuanHulio** [comment]
@LewisTehMinerz okay so it builds using the master branch test, however, adding a test for it makes test hang forever

**Comment by LewisTehMinerz** [comment]
will hang for 10m because circleci will auto kill any step if it hangs if i remember correctly, or is that mocha?

either way, are you *sure* that the MULTI command is working fine? because it will fail in the case that the MULTI command breaks mid-run.

**Comment by KuanHulio** [comment]
I don't know, I know for a fact that the master branch test builds, but can
you test this IRL?

**Comment by LewisTehMinerz** [comment]
i'll try to, but exams might catch up to me 😓

**Comment by KuanHulio** [comment]
While the MULTI test doesn't work, I'm gonna push it anyway, we can revert it in typical git command line

**Pull request merged**
