### PR TITLE
Run tests sequentially

### PR DESCRIPTION
**Pull request by lpinca**
#### Describe what your pull request does

Wait for each test to complete before running the next one.

#### Why should it be accepted?

Because the assumption is that tests are run sequentially but currently they aren't.

#### I have
* [x] made sure there are no pull requests that add this functionality.
* [ ] read and followed the [contribution guidelines](https://github.com/LewisTehMinerz/PancakeDB/blob/master/CONTRIBUTING.md).
* [ ] read and followed the [Code of Conduct](https://github.com/LewisTehMinerz/PancakeDB/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by lpinca** [comment]
I can change the target branch and rebase if needed.

**Comment by KuanHulio** [comment]
@lpinca The build is failing. 

Reference:
```
#!/bin/bash -eo pipefail
npm run test
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info lifecycle pancakedb@0.0.1-dev~pretest: pancakedb@0.0.1-dev
npm info lifecycle pancakedb@0.0.1-dev~test: pancakedb@0.0.1-dev

> pancakedb@0.0.1-dev test /home/circleci/repo
> mocha --reporter mocha-circleci-reporter --bail



  Client
    ✓ should connect
    AUTH
      ✓ should deny access when using an incorrect password
      ✓ should grant access when using a correct password
    CREATE
      DATABASE
        ✓ should create 1 database by the name test_database
        ✓ should create 1 database by the name test_database1
      TABLE
        ✓ should create a table by the name test_table in the database test_database
        ✓ should create a table by the name test_table1 in the database test_database1
    INSERT
      ✓ should insert a record into the table test_table in the database test_database
    MERGE
      DATABASE
        1) should merge the two databases named test_database and test_database1


  8 passing (85ms)
  1 failing

  1) Client MERGE DATABASE should merge the two databases named test_database and test_database1:

      Uncaught AssertionError: expected "./databases/test_database.json" to contain ""test_table1":[]"
      + expected - actual

      -{"type":"Buffer","data":[123,34,116,101,115,116,95,116,97,98,108,101,49,34,58,91,93,125]}
      +"test_table1":[]
      
      at WebSocket.ws.once.m (test/test.js:141:71)
      at Receiver._receiver.onmessage (node_modules/ws/lib/websocket.js:145:47)
      at Receiver.dataMessage (node_modules/ws/lib/receiver.js:430:14)
      at Receiver.getData (node_modules/ws/lib/receiver.js:368:12)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:164:16)
      at Receiver.add (node_modules/ws/lib/receiver.js:138:10)
      at Socket._ultron.on (node_modules/ws/lib/websocket.js:143:54)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at TCP.onread (net.js:561:20)




npm info lifecycle pancakedb@0.0.1-dev~test: Failed to exec test script
npm ERR! Linux 4.4.0-111-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pancakedb@0.0.1-dev test: `mocha --reporter mocha-circleci-reporter --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pancakedb@0.0.1-dev test script 'mocha --reporter mocha-circleci-reporter --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pancakedb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mocha-circleci-reporter --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pancakedb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pancakedb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/circleci/.npm/_logs/2018-01-23T17_09_46_174Z-debug.log
Exited with code 1
```

**Comment by lpinca** [comment]
The development and master branch are not even so it's pretty obvious that this doesn't work against development :)

**Comment by lpinca** [comment]
@KuanHulio can you rebase development against master or merge master on development?

**Comment by LewisTehMinerz** [comment]
@KuanHulio is working on it.

**Comment by KuanHulio** [comment]
@lpinca Your test still fails. I'm assuming it's a simple fix.

Reference:
```
#!/bin/bash -eo pipefail
npm run test
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info lifecycle pancakedb@0.0.1-dev~pretest: pancakedb@0.0.1-dev
npm info lifecycle pancakedb@0.0.1-dev~test: pancakedb@0.0.1-dev

> pancakedb@0.0.1-dev test /home/circleci/repo
> mocha --reporter mocha-circleci-reporter --bail



  Client
    ✓ should connect
    AUTH
      ✓ should deny access when using an incorrect password
      ✓ should grant access when using a correct password
    CREATE
      DATABASE
        ✓ should create 1 database by the name test_database
        ✓ should create 1 database by the name test_database1
      TABLE
        ✓ should create a table by the name test_table in the database test_database
        ✓ should create a table by the name test_table1 in the database test_database1
    INSERT
      ✓ should insert a record into the table test_table in the database test_database
    MERGE
      DATABASE
        ✓ should merge the two databases named test_database and test_database1
    LIST
      DATABASES
        ✓ should send an array of all the databases and the array should contain test_database
      TABLES
        ✓ should send an array of all the tables in the database test_database and the array should contain test_table
      RECORDS
        ✓ should send an array of all the records in the table test_table in the database test_database and the array should contain test_record
    DELETE
      TABLE
        ✓ should delete the table test_table from the database test_database
      DATABASE
        ✓ should delete database test_database
        ✓ should delete database test_database1
    SHUTDOWN
      1) should shut down the PancakeDB server


  15 passing (86ms)
  1 failing

  1) Client SHUTDOWN should shut down the PancakeDB server:
     Uncaught Error: read ECONNRESET
      at exports._errnoException (util.js:1050:11)
      at TCP.onread (net.js:582:26)




npm info lifecycle pancakedb@0.0.1-dev~test: Failed to exec test script
npm ERR! Linux 4.4.0-111-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pancakedb@0.0.1-dev test: `mocha --reporter mocha-circleci-reporter --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pancakedb@0.0.1-dev test script 'mocha --reporter mocha-circleci-reporter --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pancakedb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mocha-circleci-reporter --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pancakedb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pancakedb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/circleci/.npm/_logs/2018-01-23T18_44_11_784Z-debug.log
Exited with code 1
```

**Comment by lpinca** [comment]
If you reset the development branch to cabf0429ca8a750190b5f38b9ce71612c89591fe this should apply cleanly.

**Comment by LewisTehMinerz** [comment]
Reverted -- can merge.

**Comment by LewisTehMinerz** [comment]
Thanks for your commit!

**Pull request merged**
